
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public sealed partial class ChapterInfo : Luban.BeanBase
{
    public ChapterInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); UpgradeItemList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); UpgradeItemList.Add(_e0);}}
    }

    public static ChapterInfo DeserializeChapterInfo(ByteBuf _buf)
    {
        return new chapter.ChapterInfo(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> UpgradeItemList;
    public System.Collections.Generic.List<chapter.ChapterItem> UpgradeItemList_Ref;
   
    public const int __ID__ = -1849739686;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UpgradeItemList_Ref = new System.Collections.Generic.List<chapter.ChapterItem>();
        foreach (var _v in UpgradeItemList) { UpgradeItemList_Ref.Add(tables.TbChapterItem.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "upgradeItemList:" + Luban.StringUtil.CollectionToString(UpgradeItemList) + ","
        + "}";
    }
}
}

