
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public sealed partial class ChapterItem : Luban.BeanBase
{
    public ChapterItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Location = _buf.ReadString();
        {int n0 = _buf.ReadSize(); LevelList = new System.Collections.Generic.List<chapter.ChapterItemLevel>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { chapter.ChapterItemLevel _e0;  _e0 = global::GameConfig.chapter.ChapterItemLevel.DeserializeChapterItemLevel(_buf); LevelList.Add(_e0);}}
    }

    public static ChapterItem DeserializeChapterItem(ByteBuf _buf)
    {
        return new chapter.ChapterItem(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string Location;
    public readonly System.Collections.Generic.List<chapter.ChapterItemLevel> LevelList;
   
    public const int __ID__ = -1849733953;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LevelList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "location:" + Location + ","
        + "levelList:" + Luban.StringUtil.CollectionToString(LevelList) + ","
        + "}";
    }
}
}

