
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public sealed partial class ChapterEntity : Luban.BeanBase
{
    public ChapterEntity(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Location = _buf.ReadString();
        SortOrder = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); UpgradeList = new System.Collections.Generic.List<chapter.EntityDetail>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { chapter.EntityDetail _e0;  _e0 = global::GameConfig.chapter.EntityDetail.DeserializeEntityDetail(_buf); UpgradeList.Add(_e0);}}
    }

    public static ChapterEntity DeserializeChapterEntity(ByteBuf _buf)
    {
        return new chapter.ChapterEntity(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源位置
    /// </summary>
    public readonly string Location;
    public readonly int SortOrder;
    /// <summary>
    /// 升级列表(等级+价格+经验)
    /// </summary>
    public readonly System.Collections.Generic.List<chapter.EntityDetail> UpgradeList;
   
    public const int __ID__ = 402520719;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UpgradeList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "location:" + Location + ","
        + "sortOrder:" + SortOrder + ","
        + "upgradeList:" + Luban.StringUtil.CollectionToString(UpgradeList) + ","
        + "}";
    }
}
}

