
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public sealed partial class ChapterItemLevel : Luban.BeanBase
{
    public ChapterItemLevel(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        Price = _buf.ReadInt();
    }

    public static ChapterItemLevel DeserializeChapterItemLevel(ByteBuf _buf)
    {
        return new chapter.ChapterItemLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -1472430587;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "price:" + Price + ","
        + "}";
    }
}
}

