
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public sealed partial class ChapterConfig : Luban.BeanBase
{
    public ChapterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); EntityList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EntityList.Add(_e0);}}
    }

    public static ChapterConfig DeserializeChapterConfig(ByteBuf _buf)
    {
        return new chapter.ChapterConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 物品列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> EntityList;
    public System.Collections.Generic.List<chapter.ChapterEntity> EntityList_Ref;
   
    public const int __ID__ = 346003950;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        EntityList_Ref = new System.Collections.Generic.List<chapter.ChapterEntity>();
        foreach (var _v in EntityList) { EntityList_Ref.Add(tables.TbChapterEntity.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "entityList:" + Luban.StringUtil.CollectionToString(EntityList) + ","
        + "}";
    }
}
}

