
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public sealed partial class EntityDetail : Luban.BeanBase
{
    public EntityDetail(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        Price = _buf.ReadInt();
        Exp = _buf.ReadInt();
    }

    public static EntityDetail DeserializeEntityDetail(ByteBuf _buf)
    {
        return new chapter.EntityDetail(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 经验
    /// </summary>
    public readonly int Exp;
   
    public const int __ID__ = 461789749;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "price:" + Price + ","
        + "exp:" + Exp + ","
        + "}";
    }
}
}

