
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public partial class TbChapterInfo
{
    private readonly System.Collections.Generic.Dictionary<int, chapter.ChapterInfo> _dataMap;
    private readonly System.Collections.Generic.List<chapter.ChapterInfo> _dataList;
    
    public TbChapterInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, chapter.ChapterInfo>(n);
        _dataList = new System.Collections.Generic.List<chapter.ChapterInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            chapter.ChapterInfo _v;
            _v = global::GameConfig.chapter.ChapterInfo.DeserializeChapterInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, chapter.ChapterInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<chapter.ChapterInfo> DataList => _dataList;

    public chapter.ChapterInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public chapter.ChapterInfo Get(int key) => _dataMap[key];
    public chapter.ChapterInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

