
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public partial class TbChapterItem
{
    private readonly System.Collections.Generic.Dictionary<int, chapter.ChapterItem> _dataMap;
    private readonly System.Collections.Generic.List<chapter.ChapterItem> _dataList;
    
    public TbChapterItem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, chapter.ChapterItem>(n);
        _dataList = new System.Collections.Generic.List<chapter.ChapterItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            chapter.ChapterItem _v;
            _v = global::GameConfig.chapter.ChapterItem.DeserializeChapterItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, chapter.ChapterItem> DataMap => _dataMap;
    public System.Collections.Generic.List<chapter.ChapterItem> DataList => _dataList;

    public chapter.ChapterItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public chapter.ChapterItem Get(int key) => _dataMap[key];
    public chapter.ChapterItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

