
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chapter
{
public partial class TbChapterConfig
{
    private readonly System.Collections.Generic.Dictionary<int, chapter.ChapterConfig> _dataMap;
    private readonly System.Collections.Generic.List<chapter.ChapterConfig> _dataList;
    
    public TbChapterConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, chapter.ChapterConfig>(n);
        _dataList = new System.Collections.Generic.List<chapter.ChapterConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            chapter.ChapterConfig _v;
            _v = global::GameConfig.chapter.ChapterConfig.DeserializeChapterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, chapter.ChapterConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<chapter.ChapterConfig> DataList => _dataList;

    public chapter.ChapterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public chapter.ChapterConfig Get(int key) => _dataMap[key];
    public chapter.ChapterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

