
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private chapter.TbChapterItem m_TbChapterItem;
    public chapter.TbChapterItem TbChapterItem 
    {
        get
        {
            if (m_TbChapterItem == null)
            {
                m_TbChapterItem = new chapter.TbChapterItem(defaultLoader("chapter_tbchapteritem"));
                m_TbChapterItem.ResolveRef(this);
            }
            return m_TbChapterItem;
        }
        set
        {
            m_TbChapterItem = value;
            m_TbChapterItem.ResolveRef(this);
        }
    }
    private chapter.TbChapterInfo m_TbChapterInfo;
    public chapter.TbChapterInfo TbChapterInfo 
    {
        get
        {
            if (m_TbChapterInfo == null)
            {
                m_TbChapterInfo = new chapter.TbChapterInfo(defaultLoader("chapter_tbchapterinfo"));
                m_TbChapterInfo.ResolveRef(this);
            }
            return m_TbChapterInfo;
        }
        set
        {
            m_TbChapterInfo = value;
            m_TbChapterInfo.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
