
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private chapter.TbChapterConfig m_TbChapterConfig;
    public chapter.TbChapterConfig TbChapterConfig 
    {
        get
        {
            if (m_TbChapterConfig == null)
            {
                m_TbChapterConfig = new chapter.TbChapterConfig(defaultLoader("chapter_tbchapterconfig"));
                m_TbChapterConfig.ResolveRef(this);
            }
            return m_TbChapterConfig;
        }
        set
        {
            m_TbChapterConfig = value;
            m_TbChapterConfig.ResolveRef(this);
        }
    }
    private chapter.TbChapterEntity m_TbChapterEntity;
    public chapter.TbChapterEntity TbChapterEntity 
    {
        get
        {
            if (m_TbChapterEntity == null)
            {
                m_TbChapterEntity = new chapter.TbChapterEntity(defaultLoader("chapter_tbchapterentity"));
                m_TbChapterEntity.ResolveRef(this);
            }
            return m_TbChapterEntity;
        }
        set
        {
            m_TbChapterEntity = value;
            m_TbChapterEntity.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
